Include QDesktopWidget for call via QApplication
Our calling of QApplication()::desktop()->screenGeometry() showcases an
interesting change in Qt: It seems, not all types are fully declared by default
any more and we end up with only the forward declaration. The qapplication.h
header reads:

[...]
class QDesktopWidget;
[...]
static QDesktopWidget *desktop();

So it seems, in order to use methods returning QDesktopWidget, we need to
explicitly include the header to get the full type declared and avoid this
error:

make[1]: Entering directory '/sctime/src'
g++ -c -pipe -O2 -std=gnu++11 -D_REENTRANT -Wall -W -fPIC -DAPP_VERSION=1.2.1 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o timemainwindow.o timemainwindow.cpp
timemainwindow.cpp: In member function ‘void TimeMainWindow::resizeToIfSensible(QDialog*, const QPoint&, const QSize&)’:
timemainwindow.cpp:1228:47: error: invalid use of incomplete type ‘class QDesktopWidget’
   QRect screenGeometry(QApplication::desktop()->screenGeometry());
                                               ^~
In file included from /usr/include/qt5/QtWidgets/QApplication:1,
                 from timemainwindow.cpp:22:
/usr/include/qt5/QtWidgets/qapplication.h:57:7: note: forward declaration of ‘class QDesktopWidget’
 class QDesktopWidget;
       ^~~~~~~~~~~~~~
make[1]: *** [Makefile:772: timemainwindow.o] Error 1
make[1]: Leaving directory '/sctime/src'
make: *** [Makefile:45: sub-src-make_first] Error 2

Signed-off-by: Michael Weiser <michael.weiser@gmx.de>