Add QSet header for type completeness
Our header includes aren't complete. This is masked by our use of
precompiled headers because every source file indirectly seems to
include everything listed in stable.h. This leads to errors like this
when disabling precompiled headers. Adding a number of headers to fix
compile without precompiled headers.

make[1]: Entering directory '/sctime/src'
g++ -c -pipe -O2 -std=gnu++11 -D_REENTRANT -Wall -W -fPIC -DAPP_VERSION=1.2.1 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o abteilungsliste.o abteilungsliste.cpp
In file included from eintragsliste.h:27,
                 from abteilungsliste.h:29,
                 from abteilungsliste.cpp:18:
unterkontoeintrag.h:33:17: error: field ‘m_achievedSpecialRemunSet’ has incomplete type ‘QSet<QString>’
   QSet<QString> m_achievedSpecialRemunSet;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt5/QtCore/qglobal.h:1194,
                 from /usr/include/qt5/QtCore/qchar.h:43,
                 from /usr/include/qt5/QtCore/qstring.h:48,
                 from /usr/include/qt5/QtCore/qdatetime.h:44,
                 from /usr/include/qt5/QtCore/QDateTime:1,
                 from abteilungsliste.h:23,
                 from abteilungsliste.cpp:18:
/usr/include/qt5/QtCore/qtypeinfo.h:197:1: note: declaration of ‘class QSet<QString>’
 Q_DECLARE_MOVABLE_CONTAINER(QSet);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:617: abteilungsliste.o] Error 1
make[1]: Leaving directory '/sctime/src'
make: *** [Makefile:45: sub-src-make_first] Error 2

Signed-off-by: Michael Weiser <michael.weiser@gmx.de>